### PR TITLE
 Add options to wrap around when moving windows to the next screen

### PR DESCRIPTION
**Pull request by pdecat**

### CODE REVIEW

**Comment by negesti** [comment]
and thank you very much for fixing all the typos/my bad english !

**Comment by pdecat** [comment]
> Sry for the late response haven't noticed the PR...

No pb ;)

> Maybe I miss something but why do we need an additional keyboard binding?
> Modifying the existing code and move to the first/last screen if the index is out of bounds would do the same?

I went with a new binding as not all people may like this behavior.
Maybe making this an option to wrap around instead of a new binding would be a better alternative.

**Comment by negesti** [comment]
An option sounds nice.

**Comment by pdecat** [comment]
Rebased on develop branch for gnome 3.38 support. I'll try to revive this PR...

**Comment by Merrit** [comment]
I'd love to have this feature, is there something that needs to be done to ready this PR?

Happy to help out :wave:

**Comment by pdecat** [comment]
Hi @Merrit, this PR was ready and working for me, the only change expected would be to modify how it is configured (i.e. [make it an option to wrap around  instead of a new binding](https://github.com/negesti/gnome-shell-extensions-negesti/pull/168#issuecomment-548238934)).

However, I no longer use more than one display on Gnome, it had many usability, performance and stability issues from my experience. I switched to a single _big_ 32" 4k display a few months ago and all is better.

Feel free to take on the work if you want.

**Pull request closed without merging**
